# Example GitHub Actions Workflow for Docker Bake Multi-Arch Build
# 
# To use this workflow, copy it to .github/workflows/docker-bake.yml

name: Docker Bake Multi-Arch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Bake configuration
        run: docker buildx bake --print

      - name: Print multi-architecture build configuration
        run: docker buildx bake --print app

      # Uncomment to build and load the native architecture image
      # - name: Build for native architecture
      #   run: docker buildx bake app

      # Uncomment to push to a registry (requires login)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Build and push
      #   run: docker buildx bake app --push --set app.tags=your-registry/image:tag
